### ISSUE TITLE
Could not connect to DB of v12.0

### ISSUE THREAD

**Issue by fishfree** [opencast/opencast-docker#182] opened 2022-06-19 02:46 UTC
I run the `docker-compose -p opencast-allinone -f docker-compose/docker-compose.allinone.mariadb.yml up -d && docker-compose logs -f`,  it showed errors as below, and the Opencast service could not start.
```
docker-compose-opencast-1       | Could not connect to DB
docker-compose-opencast-1       | Run opencast_main_init
docker-compose-opencast-1       | Run opencast_tz_set
docker-compose-opencast-1       |   Setting timezone to UTC
docker-compose-opencast-1       | Found custom config in /etc/opencast
docker-compose-opencast-1       | Run opencast_main_sync_config
docker-compose-opencast-1       | Run opencast_main_configure
docker-compose-opencast-1       | Run opencast_opencast_configure
docker-compose-opencast-1       | Run opencast_elasticsearch_configure
docker-compose-opencast-1       | Run opencast_db_configure
docker-compose-opencast-1       | Run opencast_mariadb_configure
docker-compose-opencast-1       | Run opencast_jdbc_configure
docker-compose-opencast-1       | Run opencast_db_trytoconnect
docker-compose-opencast-1       | Run opencast_jdbc_trytoconnect
docker-compose-opencast-1       | Try to connect to DB (1/25) FAILED
docker-compose-opencast-1       | Try to connect to DB (2/25) FAILED
docker-compose-opencast-1       | Try to connect to DB (3/25) FAILED
docker-compose-opencast-1       | Try to connect to DB (4/25) FAILED
docker-compose-opencast-1       | Try to connect to DB (5/25) FAILED
docker-compose-opencast-1       | Try to connect to DB (6/25) FAILED
docker-compose-opencast-1       | Try to connect to DB (7/25) FAILED
docker-compose-opencast-1       | Try to connect to DB (8/25) FAILED
docker-compose-opencast-1       | Try to connect to DB (9/25) FAILED
docker-compose-opencast-1       | Try to connect to DB (10/25) FAILED
docker-compose-opencast-1       | Try to connect to DB (11/25) FAILED
docker-compose-opencast-1       | Try to connect to DB (12/25) FAILED
docker-compose-opencast-1       | Try to connect to DB (13/25) FAILED
docker-compose-opencast-1       | Try to connect to DB (14/25) FAILED
docker-compose-opencast-1       | Try to connect to DB (15/25) FAILED
docker-compose-opencast-1       | Try to connect to DB (16/25) FAILED
docker-compose-opencast-1       | Try to connect to DB (17/25) FAILED
docker-compose-opencast-1       | Try to connect to DB (18/25) FAILED
docker-compose-opencast-1       | Try to connect to DB (19/25) FAILED
docker-compose-opencast-1       | Try to connect to DB (20/25) FAILED
docker-compose-opencast-1       | Try to connect to DB (21/25) FAILED
docker-compose-opencast-1       | Try to connect to DB (22/25) FAILED
docker-compose-opencast-1       | Try to connect to DB (23/25) FAILED
docker-compose-opencast-1       | Try to connect to DB (24/25) FAILED
docker-compose-opencast-1       | Try to connect to DB (25/25) FAILED
docker-compose-opencast-1       | Could not connect to DB
```

**Comment by mtneug** [comment] 2022-07-01 17:33
@fishfree thank you for the report. I will look into it.

**Comment by mtneug** [comment] 2022-08-03 17:39
Apart from that your example command will not work (should be

```sh
docker-compose -p opencast-allinone -f docker-compose/docker-compose.allinone.mariadb.yml up -d && docker-compose -p opencast-allinone -f docker-compose/docker-compose.allinone.mariadb.yml logs -f
```

or simply 

```sh
docker-compose -p opencast-allinone -f docker-compose/docker-compose.allinone.mariadb.yml up
```
), I cannot reproduce the error. Do you see log output from MariaDB?

**Comment by mtneug** [comment] 2022-08-03 21:16
I'm closing this for now. Feel free to reopen if this is still an issue.

**Closed by mtneug** 2022-08-03 21:16 UTC
